defmodule PgFlow.Repo.Migrations.CompileDispatchStep do
  @moduledoc """
  Compiles the 'dispatch_step' job definition into the database.

  This migration creates:
  - The flow record in pgflow.flows (with flow_type = 'job')
  - The PGMQ queue for this job
  - The step definition

  Generated by: mix pgflow.gen.job_migration
  """
  use Ecto.Migration

  def up do
    execute("SELECT pgflow.create_flow('dispatch_step', 1, 1, 60)")

    execute(
      "SELECT pgflow.add_step('dispatch_step', 'dispatch', ARRAY[]::text[], 1, 1, 60, NULL, 'single')"
    )

    execute("UPDATE pgflow.flows SET flow_type = 'job' WHERE flow_slug = 'dispatch_step'")
  end

  def down do
    execute("DELETE FROM pgflow.deps WHERE flow_slug = 'dispatch_step'")
    execute("DELETE FROM pgflow.steps WHERE flow_slug = 'dispatch_step'")
    execute("DELETE FROM pgflow.flows WHERE flow_slug = 'dispatch_step'")
    execute("SELECT pgmq.drop_queue('dispatch_step')")
  end
end
