defmodule DripDrop.Web.UnsubscribePlug do
  @moduledoc """
  Handles RFC 8058 one-click unsubscribe URLs generated by DripDrop.
  """

  import Plug.Conn

  alias DripDrop.{Suppressions, UnsubscribeToken}

  @doc """
  Returns Plug initialization options unchanged.
  """
  @spec init(term()) :: term()
  def init(opts), do: opts

  @doc """
  Verifies the unsubscribe token in the path and records a suppression.
  """
  @spec call(Plug.Conn.t(), term()) :: Plug.Conn.t()
  def call(%Plug.Conn{path_info: [token | _rest]} = conn, _opts) do
    case UnsubscribeToken.verify(token) do
      {:ok, payload} -> suppress(conn, payload)
      {:error, reason} -> error(conn, 400, "invalid unsubscribe token: #{inspect(reason)}")
    end
  end

  def call(conn, _opts), do: error(conn, 404, "unsubscribe token missing")

  defp suppress(conn, payload) do
    attrs = %{
      tenant_key: Map.get(payload, :tenant_key),
      channel: Map.fetch!(payload, :channel),
      recipient: Map.fetch!(payload, :recipient),
      reason: "unsubscribe",
      source: "one_click",
      metadata: %{"token" => "verified"}
    }

    case Suppressions.suppress(attrs) do
      {:ok, _suppression} -> text(conn, 200, "unsubscribed")
      {:error, changeset} -> error(conn, 422, "unsubscribe failed: #{inspect(changeset.errors)}")
    end
  end

  defp text(conn, status, body) do
    conn
    |> put_resp_content_type("text/plain")
    |> send_resp(status, body)
    |> halt()
  end

  defp error(conn, status, body), do: text(conn, status, body)
end
