import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :dripdrop_demo, DripdropDemoWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :dripdrop_demo, DripdropDemoWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Keep the deployed demo fully self-contained: run the loopback mock-hooks
# server on 127.0.0.1 so seeded HTTP/webhook/Slack adapters resolve without
# making any external API calls.
config :dripdrop_demo, start_mock_hooks?: true

# Swoosh API client is configured for any future HTTP-based adapter. The
# active mailer (set in config.exs) is `Swoosh.Adapters.Local`, which keeps
# emails in memory so the demo can preview them.
config :swoosh, api_client: Swoosh.ApiClient.Req
config :swoosh, local: true

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
