defmodule DripdropDemo.Repo.Migrations.AddPgflowHelpers do
  @moduledoc """
  Installs PgFlow extension SQL functions in the pgflow schema.

  Generated by: mix pgflow.gen.helpers_migration
  """
  use Ecto.Migration

  def up do
    PgFlow.HelpersMigration.up()
  end

  def down do
    PgFlow.HelpersMigration.down()
  end
end
