defmodule DripdropDemo.Repo.Migrations.UpgradeDripdrop do
  @moduledoc """
  Applies pending DripDrop library migrations.

  Generated by: `mix dripdrop.gen.migration`

  DripDrop migrations are vendored as versioned SQL under
  `priv/dripdrop/sql/versions`. `DripDrop.Migration.up/0` applies any
  version newer than the database's current `dripdrop.dripdrop_version`.
  """
  use Ecto.Migration

  def up do
    DripDrop.Migration.up()
  end

  def down do
    DripDrop.Migration.down()
  end
end
