defmodule DripdropDemo.Repo.Migrations.SetupDripdrop do
  @moduledoc """
  Installs DripDrop's messaging sequence schema.

  Generated by: `mix dripdrop.setup`

  SQL sources are vendored inside DripDrop:
    - priv/dripdrop/sql/versions/v01/v01_up.sql

  `DripDrop.Migration.up/0` runs via EctoEvolver, tracks the installed
  version through `dripdrop.dripdrop_version`, and is idempotent when the
  latest version is already present.

  Prerequisites (applied as earlier migrations):
    1. Postgres extensions — `mix pgflow.gen.postgres_extensions_migration`
    2. pgmq schema + functions — `mix pgflow.gen.pgmq_migration`
    3. PgFlow core + helpers — `mix pgflow.setup`
  """
  use Ecto.Migration

  def up do
    DripDrop.Migration.up()
  end

  def down do
    DripDrop.Migration.down()
  end
end
