defmodule PgFlow.Repo.Migrations.CompileCronTick do
  @moduledoc """
  Compiles the 'cron_tick' job definition into the database.

  This migration creates:
  - The flow record in pgflow.flows (with flow_type = 'job')
  - The PGMQ queue for this job
  - The step definition

  Generated by: mix pgflow.gen.job_migration
  """
  use Ecto.Migration

  def up do
    execute "SELECT pgflow.create_flow('cron_tick', 1, 1, 60)"

    execute "SELECT pgflow.add_step('cron_tick', 'tick', ARRAY[]::text[], 1, 1, 60, NULL, 'single')"

    execute "UPDATE pgflow.flows SET flow_type = 'job' WHERE flow_slug = 'cron_tick'"
  end

  def down do
    execute "DELETE FROM pgflow.deps WHERE flow_slug = 'cron_tick'"
    execute "DELETE FROM pgflow.steps WHERE flow_slug = 'cron_tick'"
    execute "DELETE FROM pgflow.flows WHERE flow_slug = 'cron_tick'"
    execute "SELECT pgmq.drop_queue('cron_tick')"
  end
end
