defmodule PgFlow.Repo.Migrations.CompilePruneSequenceRuns do
  @moduledoc """
  Compiles the 'prune_sequence_runs' job definition into the database.

  This migration creates:
  - The flow record in pgflow.flows (with flow_type = 'job')
  - The PGMQ queue for this job
  - The step definition

  Generated by: mix pgflow.gen.job_migration
  """
  use Ecto.Migration

  def up do
    execute "SELECT pgflow.create_flow('prune_sequence_runs', 1, 1, 60)"

    execute "SELECT pgflow.add_step('prune_sequence_runs', 'prune_sequence_runs', ARRAY[]::text[], 1, 1, 60, NULL, 'single')"

    execute """
    DO $do$
    BEGIN
      IF to_regprocedure('cron.schedule(text,text,text)') IS NOT NULL THEN
        PERFORM cron.schedule(
          'pgflow:prune_sequence_runs',
          '0 3 * * *',
          $$SELECT pgflow.start_flow('prune_sequence_runs', '{}'::jsonb)$$
        );
      END IF;
    END
    $do$
    """

    execute "UPDATE pgflow.flows SET flow_type = 'job' WHERE flow_slug = 'prune_sequence_runs'"
  end

  def down do
    execute """
    DO $do$
    BEGIN
      IF to_regprocedure('cron.unschedule(text)') IS NOT NULL THEN
        PERFORM cron.unschedule('pgflow:prune_sequence_runs');
      END IF;
    END
    $do$
    """

    execute "DELETE FROM pgflow.deps WHERE flow_slug = 'prune_sequence_runs'"
    execute "DELETE FROM pgflow.steps WHERE flow_slug = 'prune_sequence_runs'"
    execute "DELETE FROM pgflow.flows WHERE flow_slug = 'prune_sequence_runs'"
    execute "SELECT pgmq.drop_queue('prune_sequence_runs')"
  end
end
